services:
  web01:
    build:
      context: ./site1
      dockerfile: Dockerfile
    image: web01
    container_name: web01
    networks:
      - teste-asa-1b
  web02:
    build:
      context: ./site2
      dockerfile: Dockerfile
    image: web02
    container_name: web02
    networks:
      - teste-asa-1b
  web03:
    build:
      context: ./site3
      dockerfile: Dockerfile
    image: web03
    container_name: web03
    networks:
      - teste-asa-1b
  proxy:
      build:
        context: ./proxy
        dockerfile: Dockerfile
      image: proxy
      container_name: proxy
      ports:
        - "8080:80"
      depends_on:
        - web01
        - web02
        - web03
      networks:
        - teste-asa-1b
  dns:
    build:
      context: ./bind/primario
      dockerfile: Dockerfile
    image: primario
    container_name: primario
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - teste-asa-1b
  dnns:
    build:
      context: ./bind/secundario
      dockerfile: Dockerfile
    image: secundario
    container_name: secundario
    ports:
      - "5353:53/tcp"
      - "5353:53/udp"
    networks:
      - teste-asa-1b    
#Docker Networks
networks:
  teste-asa-1b:
    driver: bridge
