services:
  web01:
    build:
      context: .
      dockerfile: site1/Dockerfile
    image: web01
    container_name: c01
    networks:
      - asa-network

  web02:
    build:
      context: .
      dockerfile: site2/Dockerfile
    image: web02
    container_name: c02
    networks:
      - asa-network

  web03:
    build:
      context: .
      dockerfile: site3/Dockerfile
    image: web03
    container_name: c03
    networks:
      - asa-network

  proxy:
    build:
      context: .
      dockerfile: proxy/Dockerfile
    image: proxy
    container_name: proxy
    ports:
      - "8080:80"
    depends_on:
      - web01
      - web02
      - web03
    networks:
      - asa-network

# Docker Networks
networks:
  asa-network:
    driver: bridge
